### ISSUE TITLE
wme bamg amku mamin popowi leadernya gaada [BUG] 

### ISSUE THREAD

**Issue by rpro29524** [tfkhdyt/popclick#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tfkhdyt** [comment]
Baca readme

**Comment by rpro29524** [comment]
> Baca readme

dmn?

**Comment by tfkhdyt** [comment]
> > Baca readme
> 
> dmn?

Di [jonggol](https://github.com/tfkhdyt/popclick)
