### ISSUE TITLE
Pertanyaan

### ISSUE THREAD

**Issue by usernamedoesntexist** [tfkhdyt/popclick#5]
bang gimana caranya supaya user ngak bisa mengubah current score nya?

**Comment by tfkhdyt** [comment]
Current score local atau leaderboard?

**Comment by usernamedoesntexist** [comment]
current

> Current score local atau leaderboard?

current score bang

**Comment by tfkhdyt** [comment]
Cek aja [di sini](https://github.com/tfkhdyt/popclick/blob/main/src/container/Counter.jsx)

**Comment by usernamedoesntexist** [comment]
pake cookie kh bang?

**Comment by tfkhdyt** [comment]
Iya untuk local score pake cookie

**Comment by usernamedoesntexist** [comment]
caranya supaya user ngak bisa mengubah cookienya gimana bang?

**Comment by tfkhdyt** [comment]
Sebenarnya bisa kalau cookienya di ubah langsung, tapi gak bakal ngaruh ke leaderboard

**Comment by usernamedoesntexist** [comment]
disaya cookie nya gk bisa diubah bang, pas di refresh cookie balik lagi

**Comment by tfkhdyt** [comment]
Oh cookienya kereset lagi?

**Comment by usernamedoesntexist** [comment]
iyh bang,
kalau popcat kan jelas kalau pake jwt jadi gk bakal bisa diubah

**Comment by tfkhdyt** [comment]
Cek [line 39](https://github.com/tfkhdyt/popclick/blob/main/src/container/Counter.jsx)

**Comment by tfkhdyt** [comment]
Expires nya harus diatur dulu

**Comment by usernamedoesntexist** [comment]
ok, bang paham''
