### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by JastinXyz** [tfkhdyt/popclick#8]
score provinsi di leaderboard kadang kadang ngurang sendiri posisi juga jadi turun

**Comment by tfkhdyt** [comment]
Score yang gak masuk akal memang saya kurangi 😁

**Comment by JastinXyz** [comment]
kedepannya? gmna ntar klo misal banyak yg main dan semua score gk masuk akal:v

**Comment by tfkhdyt** [comment]
Udah gw limit dalam 10 detik hanya boleh 74 score yang masuk (per user)

**Comment by JastinXyz** [comment]
udh punya auto click enak eh gk bisa make keydown:v

**Comment by tfkhdyt** [comment]
Awokawokawok mpos
